import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@repo/redux-utils";
import localFont from "next/font/local";
import { Toaster } from "@repo/ui";

export const metadata: Metadata = {
  title: "ResumeBeat",
  description: "Generated by create next app",
};
const londrina = localFont({
  src: "../public/fonts/Londrina_Outline/LondrinaOutline-Regular.ttf",
  variable: "--font-londrina",
});
const wittgenstein = localFont({
  src: "../public/fonts/Wittgenstein/Wittgenstein-VariableFont_wght.ttf",
  variable: "--font-wittgenstein",
});
const vanchrome = localFont({
  src: "../public/fonts/vanchrome edge.otf",
  variable: "--font-vanchrome",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${londrina.variable} ${wittgenstein.variable} ${vanchrome.variable}`}
      >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
